name: firebase_app_check_example
description: Firebase App Check example application.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <4.0.0'

dependencies:
  cloud_firestore: ^4.17.1
  firebase_app_check: ^0.2.2+3
  firebase_core: ^2.30.1
  flutter:
    sdk: flutter

flutter:
  uses-material-design: true
