name: firebase_auth_example
description: Demonstrates how to use the firebase_auth plugin.

environment:
  sdk: '>=2.18.0 <4.0.0'

dependencies:
  barcode_widget: ^2.0.4
  firebase_auth: ^4.19.3
  firebase_core: ^2.30.1
  firebase_messaging: ^14.9.0
  flutter:
    sdk: flutter
  flutter_facebook_auth: ^6.0.0
  flutter_signin_button: ^2.0.0
  google_sign_in: ^6.1.0
  google_sign_in_dartio: ^0.3.0

dev_dependencies:
  http: ^1.0.0

flutter:
  uses-material-design: true
