name: firebase_performance_web
description: Web implementation of Firebase Performance monitoring.
homepage: https://github.com/firebase/flutterfire/tree/master/packages/firebase_performance/firebase_performance_web
version: 0.1.4+26

environment:
  sdk: '>=2.18.0 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  _flutterfire_internals: ^1.3.26
  firebase_core: ^2.27.1
  firebase_core_web: ^2.12.0
  firebase_performance_platform_interface: ^0.1.4+26
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  js: ^0.6.3
  web: ^0.5.1


dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  plugin:
    platforms:
      web:
        pluginClass: FirebasePerformanceWeb
        fileName: firebase_performance_web.dart
